### ISSUE TITLE
Non-AC buses abroad are missing coordinates in eGon100RE 

### ISSUE THREAD

**Issue by AmeliaNadal** [openego/eGon-data#803] opened 2022-06-08 14:23 UTC
In eGon100RE, all the buses abroad with a carrier different of 'AC' ('biogas', 'gas', 'gas for industry', 'H2', 'low voltage', 'residential rural heat', 'residential rural water tanks', 'residential urban decentral heat', 'residential urban decentral water tanks', 'services rural heat', 'services rural water tanks', 'services urban decentral heat', 'services urban decentral water tanks', 'urban central heat', 'urban central water tanks') do not have coordinates (x=0, y=0).
The coordinates are probably not set or exported correctly in/from p-e-s.

Already explained in #640.

**Comment by nesnoj** [comment] 2022-06-09 07:17
If this includes #777 and #778, you may want to close those ones?
And if this is a duplicate of #640, please close that one.

**Comment by AmeliaNadal** [comment] 2022-06-09 10:15
> If this includes #777 and #778, you may want to close those ones? And if this is a duplicate of #640, please close that one.

You're fully right, I've closed these 3 older issues.

**Closed** 2022-07-27 06:44 UTC
