### ISSUE TITLE
Sanity checks reveal deviations in eGon2035 generators

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#1072] opened 2022-12-23 01:51 UTC
Not sure if they are relevant, but task `sanity_checks.etrago-eGon2035-electricity` lists some deviations >0:

Last Hetzner run (15.12.):
- reservoir: -0.34 %
- run_of_river: -3.67 %
- oil: -63.6 %

Last Flensburg run (21.12):
- reservoir: -0.46 %
- run_of_river: -1.74 %
- oil: -63.6 %

New MaStR should not be influencing this as it used only for wind+PV. But for sake of completeness: Hetzner run **without** new MaStR, Flensburg run **with** new MaStR.

**Comment by IlkaCu** [comment] 2023-01-03 12:24
We assume that the deviations for hydro power are acceptable. If I am not mistaken the deviation for oil are caused by the sanity checks not taking chp capacities into account which are distributed somewhere else. I will open another issue for this topic and close this issue.

**Closed by IlkaCu** 2023-01-03 12:24 UTC
Labels: :bug: bug

**Comment by nesnoj** [comment] 2023-01-06 09:44
Oh, apparently I did not make myself clear in the first place: I wasn't pointing at the deviation values but the deviation between the deviation values in the 2 runs which should be equal but there were not.

In the last Hetzner run (23.12.) the numbers remain the same which makes me feel better:
- reservoir: -0.46 %
- run_of_river: -1.74 %
- oil: -63.6 %
