### ISSUE TITLE
Undefined Table, relation does not exist

### ISSUE THREAD

**Issue by nailend** [openego/eGon-data#217] opened 2021-04-15 15:19 UTC
Hey there,

just ran in an ERROR  after triggering egon-data for the first time.
I am using python 3.8 and the current dev-branch #205 

```
[2021-04-15 15:29:41,429] {taskinstance.py:1150} ERROR - (psycopg2.errors.UndefinedTable) relation "society.destatis_zensus_population_per_ha" does not exist

[SQL: 
CREATE TABLE demand.egon_demandregio_zensus_electricity (
	zensus_population_id INTEGER NOT NULL, 
	scenario VARCHAR(50) NOT NULL, 
	sector VARCHAR NOT NULL, 
	demand FLOAT, 
	PRIMARY KEY (zensus_population_id, scenario, sector), 
	FOREIGN KEY(zensus_population_id) REFERENCES society.destatis_zensus_population_per_ha (id)
)

]
```
task: create-demand-tables

temporary  fix;
replace `map_zensus_vg250 >> elec_household_demands_zensus` with  `[zensus_inside_ger, map_zensus_vg250] >> elec_household_demands_zensus`
in https://github.com/openego/eGon-data/blob/89c0f8a646dfe2b6bfc8f43f048d543a84061db7/src/egon/data/airflow/dags/pipeline.py#L228

**Comment by nailend** [comment] 2021-04-15 16:32
the temporary fix brought me here....

`[2021-04-15 17:50:09,706] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.electrical-demands-zensus 2021-04-15T15:39:50.775551+00:00 [running]> on host rli-nb-74lin.rl-institut.local
[2021-04-15 17:50:09,898] {taskinstance.py:1150} ERROR - (psycopg2.errors.UndefinedTable) relation "boundaries.egon_map_zensus_nuts3" does not exist
LINE 2:         boundaries.
                ^

[SQL: SELECT zensus_population_id, nuts3 FROM
        boundaries.
        egon_map_zensus_nuts3]`

**Comment by ClaraBuettner** [comment] 2021-04-16 06:58
Thanks for reporting the issue. There is a missing task-dependency (since demand.egon_demandregio_zensus_electricity references society.destatis_zensus_population_per_ha as a foreign key, this table has to be created in advance). 
This should be fixed in 4bcd05543be08b32eb8c5c575b760689b13d9f68 (PR #215). Until this is merged, you could cherry-pick this commit or simply run the dag again because this issue only occurs in the first run.

**Comment by nailend** [comment] 2021-04-19 11:16
Thanks for the hint this worked so far but ended up in the second error anyways. Do you also know a solution for this?

> the temporary fix brought me here....
> 
> `[2021-04-15 17:50:09,706] {logging_mixin.py:120} INFO - Running <TaskInstance: egon-data-processing-pipeline.electrical-demands-zensus 2021-04-15T15:39:50.775551+00:00 [running]> on host rli-nb-74lin.rl-institut.local [2021-04-15 17:50:09,898] {taskinstance.py:1150} ERROR - (psycopg2.errors.UndefinedTable) relation "boundaries.egon_map_zensus_nuts3" does not exist`

**Comment by gplssm** [comment] 2021-04-20 07:59
I tried to reproduce the error you reported, but I can't reproduce it exactly.

I pulled latest dev and installed it to a newly created environment. The task `create-demand-tables` ran successfully, but in the task `electrical-household-demands-zensus` I get the same error about the not existing relation.

```
[2021-04-20 09:45:43,470] {taskinstance.py:1150} ERROR - (psycopg2.errors.UndefinedTable) relation "boundaries.egon_map_zensus_nuts3" does not exist
LINE 2:         boundaries.
                ^

[SQL: SELECT zensus_population_id, nuts3 FROM
        boundaries.
        egon_map_zensus_nuts3]
(Background on this error at: http://sqlalche.me/e/13/f405)
Traceback (most recent call last):
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "boundaries.egon_map_zensus_nuts3" does not exist
LINE 2:         boundaries.
                ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/egon/data/processing/demandregio/__init__.py", line 66, in distribute_household_demands
    index_col='zensus_population_id')
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/egon/data/db.py", line 129, in select_dataframe
    df = pd.read_sql(sql, engine(), index_col=index_col)
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/pandas/io/sql.py", line 527, in read_sql
    chunksize=chunksize,
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/pandas/io/sql.py", line 1308, in read_query
    result = self.execute(*args)
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/pandas/io/sql.py", line 1176, in execute
    return self.connectable.execution_options().execute(*args, **kwargs)
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2235, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1178, in _execute_text
    parameters,
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/guido/miniconda3/envs/eGon-data-217/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "boundaries.egon_map_zensus_nuts3" does not exist
LINE 2:         boundaries.
                ^

[SQL: SELECT zensus_population_id, nuts3 FROM
        boundaries.
        egon_map_zensus_nuts3]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2021-04-20 09:45:43,475] {taskinstance.py:1194} INFO - Marking task as FAILED. dag_id=egon-data-processing-pipeline, task_id=electrical-household-demands-zensus, execution_date=20210420T072411, start_date=20210420T074543, end_date=20210420T074543
```

There is a very similar named table `egon_map_zensus_vg250`. @ClaraBuettner was this maybe renamed (and some parts were missed to adapt properly) or is this a totally different table?

**Comment by ClaraBuettner** [comment] 2021-04-20 09:59
> There is a very similar named table `egon_map_zensus_vg250`. @ClaraBuettner was this maybe renamed (and some parts were missed to adapt properly) or is this a totally different table?

Yes, the table  `egon_map_zensus_nuts3 ` was replaced by `egon_map_zensus_vg250`. Since I still have the old table, I didn't run into this error. Sorry for the confusion, I will fix this soon.

**Closed** 2021-04-20 14:09 UTC
Labels: :bug: bug
